# Generated by Django 3.2.5 on 2021-07-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telegram_user',
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='required_score_to_pass',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='quiz_answer',
        ),
        migrations.AlterModelTable(
            name='question',
            table='quiz_question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.telegramuser')),
            ],
            options={
                'db_table': 'user_result',
            },
        ),
    ]
