# Generated by Django 3.2.5 on 2021-07-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210715_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='quiz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
