# Generated by Django 3.2.5 on 2021-07-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210715_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.telegramuser'),
        ),
    ]
