# Generated by Django 3.2.5 on 2021-07-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210715_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresult',
            old_name='quiz',
            new_name='quiz_id',
        ),
        migrations.RenameField(
            model_name='userresult',
            old_name='user',
            new_name='user_id',
        ),
    ]
