# Generated by Django 3.2.5 on 2021-07-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210715_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResult',
        ),
    ]
