# Generated by Django 3.2.5 on 2021-07-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210715_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'quiz_types',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiztypes'),
        ),
    ]
