# Generated by Django 3.2.5 on 2021-07-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210716_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresult',
            name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='userresult',
            name='user_id',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='subscriptions',
            field=models.ManyToManyField(to='quiz.Subscription'),
        ),
        migrations.AddField(
            model_name='userresult',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='userresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.telegramuser'),
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
    ]
