# Generated by Django 3.2.5 on 2021-07-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210719_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text_url', models.URLField()),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiz')),
            ],
            options={
                'db_table': 'reading_topics',
            },
        ),
    ]
