# Generated by Django 3.2.5 on 2021-07-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_readingtopics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text_url', models.URLField()),
                ('audio_file', models.FileField(upload_to='')),
                ('audio_file_abs_path', models.CharField(blank=True, max_length=200)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiz')),
            ],
        ),
    ]
